name: Continuous Integration 

on: [push, pull_request]

jobs:
  testFrontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        working-directory: ./app-frontend
        run: yarn

      - name: Run ESLint
        working-directory: ./app-frontend
        run: yarn lint

      - name: Run tests
        working-directory: ./app-frontend
        run: yarn test --watchAll=false

  testBackend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        working-directory: ./
        run: yarn

      - name: Run ESLint
        working-directory: ./
        run: yarn lint
