export const API_URL = 'http://localhost:3000';

export const LOAD_WORKERS_DATA = 'LOAD_WORKERS_DATA';
export const LOAD_WORKERS_DATA_SUCCESS = 'LOAD_WORKERS_DATA_SUCCESS';
export const LOAD_WORKERS_DATA_FAILED = 'LOAD_WORKERS_DATA_FAILED';

export const LOAD_WORKER_DATA = 'LOAD_WORKER_DATA';
export const LOAD_WORKER_DATA_SUCCESS = 'LOAD_WORKER_DATA_SUCCESS';
export const LOAD_WORKER_DATA_FAILED = 'LOAD_WORKER_DATA_FAILED';

export const ADD_WORKER_DATA = 'ADD_WORKER_DATA';
export const ADD_WORKER_DATA_SUCCESS = 'ADD_WORKER_DATA_SUCCESS';
export const ADD_WORKER_DATA_FAILED = 'ADD_WORKER_DATA_FAILED';

export const EDIT_WORKER_DATA = 'EDIT_WORKER_DATA';
export const EDIT_WORKER_DATA_SUCCESS = 'EDIT_WORKER_DATA_SUCCESS';
export const EDIT_WORKER_DATA_FAILED = 'EDIT_WORKER_DATA_FAILED';

export const SET_FILTER_PARAMETERS = 'SET_FILTER_PARAMETERS';

export const EDIT_WORKER_STATE = 'EDIT_WORKER_STATE';
